name = input("whats your username?")
print ("how do you do", name)
destination = input("where do you want to vaycay?")
print (destination, "! I have a friend in", destination, "!!")
days = input("how long do you plan on staying?")
print ("only", days, "days?")
USD = input("Lets talk numbers... whats your budget in USD?")
print ("thats a lot of dough!")
currency = input("what currency will you be using?")
print ("will do!")
rate = input("what is the conversion rate for that?")
print ("thanks!")
print ("OK lets go over this, you are going to", destination, "and you are spending", days, "days there. You plan to spend", USD, ", use", currency, "currency, and the conversion rate is", rate, ". Does that sound right?")
